[project]
name = "englang-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nltk>=3.9.2",
    "pip>=25.3",
    "spacy>=3.8.11",
    "stanza>=1.11.0",
]

[build]
compiler = "msvc"
